---
title: "Data Manipulation"
author: "Katie"
date: "10/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse) 
```

## Import datasets 

```{r}
litters_data = read_csv("./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data) 
```

## Selecting 

```{r}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight) 

# start_with() calls all the variables that start with pups 
select(litters_data, litter_number, gd0_weight, starts_with("pups"))

# order is important 
select(litters_data, litter_number, group, gd0_weight)

# everything() calls for all the other variables 
select(litters_data, litter_number, group, everything())

# the - sign removes only that group variable from the dataset 
select(litters_data, -group)

# the : sign gives you all the columns between the first and second variable 
select(litters_data, litter_number, gd0_weight:pups_born_alive)

# this renames 'group' to 'GROUP' and selected these two columns  
select(litters_data, GROUP = group, litter_number) 

# rename just renames columns, it doesn't do any selecting of variables at the same time 
rename(litters_data, GROUP = group)

select(pups_data, litter_number, sex, pd_ears)
```
 
 ## Filtering 

```{r}
# using filter, the group variable should be equal to the value "Con7"
# the double equals is used to differentiate b/w an assignment; we're not trying to set group to 7, 
# but to check if the group equal to 7 
# this is a logical operator; when it's true it means keep this row 
filter(litters_data, group == "Mod8")

filter(litters_data, gd_of_birth == 20)

filter(litters_data, gd_of_birth < 20) 

filter(litters_data, pups_born_alive < 6) 

filter(litters_data, pups_born_alive < 6, group == "Con7") 

# filter(litters_data, group == "Con7" | group == "Mod8")
filter(litters_data, group %in% c("Con7", "Mod8"))

filter(litters_data, pups_born_alive >= 4, pups_born_alive <= 6) 

filter(litters_data, gd0_weight + gd18_weight < 70) 

filter(litters_data, gd0_weight > gd18_weight) 

# don't do this: 
# filter(litters_data, !is.na(gd0_weight))
drop_na(litters_data, gd0_weight)
```

## Mutate 

```{r}
mutate(litters_data, 
       wt_gain = gd18_weight - gd0_weight, 
       group = str_to_lower(group))
```

## Arrange 

```{r}
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

arrange(litters_data, pups_born_alive, gd0_weight)
```

