---
title: "Tidy Data"
author: "Katie"
date: "10/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse) 
```

## Wide to long 

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m, 
    names_to = "visit", 
    names_prefix = "bdi_score_", 
    values_to = "bdi"
  ) %>% 
  mutate(
    visit = recode(visit, "bl" = "00m")
  )
```

## Separate in litters 

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  separate(col = group, into = c("dose", "day_of_tx"), 3) %>% 
  mutate(
    dose = str_to_lower(dose), 
    wt_gain = gd18_weight - gd0_weight
  )
```

## Go untidy...

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

pivot_wider(
  analysis_result, 
  names_from = time, 
  values_from = mean
)
```

## Bind rows 

```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>% 
  mutate(movie = "fellowship_ring") 

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

lotr_data = 
  bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    female:male, 
    names_to = "sex", 
    values_to = "words"
  ) %>% 
  select(movie, race, sex, words)
```

## Join datasets

```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))
```

Try to join these datasets! 

```{r}
fas_data = 
  left_join(pup_data, litter_data, by = "litter_number") 

  full_join(pup_data, litter_data, by = "litter_number") 

## Join into the pups data everything that's in litter data using left join
## b/c we care about  pup-specific outcomes 
## and pup data lists out every single pup that we have info on. 
## It's the dataset that has everything we need, so we should 
## draw into that dataset the litter level info. 
## So we're starting with pups and pulling everything else in. 
```

